### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/InfernalMobs#2]
- [ ] Mute message #1 
- [ ] ~~Port to SQLite~~
  - [ ] ~~`loot.yml`~~
  - [ ] ~~`save.yml` (mobs)~~
- [x] Use native ItemStack serializer for  `loot.yml`
- [ ] Thief Improvement
- [x] Manage loot table in-game
- [x] Mob spawn rate improvement (direct chance percentage)

**Comment by RecursiveG** [comment]
No need to use SQLite for yaml files, as long as they can be completely loaded into memory.
